defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: enron2

test:
  <<: *defaults
  database: enron_test

# set these environment variables on your prod server
production:
	
  #uri: <%= ENV['MONGOLAB_URI'].split(',')[0] %>
  uri: "mongodb://heroku_hjqswqbt:6hi06lr0jcmrc82245pbuu5oth@ds045853-a0.mongolab.com:45853"