defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: enron

test:
  <<: *defaults
  database: enron_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGO_HOST'] %>
  port: <%= ENV['MONGO_PORT'] %>
  database: test_enron
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
  
